---
title: "quarto-practice"
format: html 
editor: visual
execute: 
  warning: false
---

suppressing warnings and messages JUST FOR THIS CODE CHUNK

```{r}
#| warning: false
#| message: false
library(tidyverse)
```

running code but not showing code or output

```{r}
#| include: false
head(starwars)
dim(starwars) # 87 entries (observations) of 14 variables
```

showing output, not code

```{r}
#| warning: false
#| echo: false # evaluates code silently
starwars %>% ggplot(aes(x = height, y = mass, col = mass)) + geom_point() + labs(x = "Height (cm)", y = "Mass (kg)")
```

```{r}
#| warning: false

starwars %>% ggplot(aes(x = height)) + geom_histogram(col = "black",fill = "darkblue", bins = 30) + theme_minimal()

```

Find summary stats for starwars characters

```{r}
sw_height_mean <- mean(starwars$height, na.rm = T)

sw_height_median <- median(starwars$height, na.rm = T)

sw_height_var <- var(starwars$height, na.rm = T)

sw_height_sd <- sd(starwars$height, na.rm = T)
```

The mean height of the characters in Starwars is `r round(sw_height_mean,1)` cm.
